all:
	javac -d . Creature.java
	javac -d . Player.java
	javac -d . Plant.java
	javac -d . Animal.java
	javac -d . Harpy.java
	javac -d . Lamia.java
	javac -d . Centaur.java
	javac -d . CreatureFactory.java
	javac -d . Universe.java
	javac -d . UniverseUsingSTL.java
	javac -d . GamePanel.java
	javac -d . UserInterface.java
	javac -d . Main.java